function FileProgress(a,c){this.fileProgressID=a.id;this.opacity=100;this.height=0;if(this.fileProgressWrapper=document.getElementById(this.fileProgressID)){this.fileProgressElement=this.fileProgressWrapper.firstChild;this.reset()}else{this.fileProgressWrapper=document.createElement("div");this.fileProgressWrapper.className="progressWrapper";this.fileProgressWrapper.id=this.fileProgressID;this.fileProgressElement=document.createElement("div");this.fileProgressElement.className="progressContainer";
var b=document.createElement("a");b.className="progressCancel";b.href="#";b.style.visibility="hidden";b.appendChild(document.createTextNode(" "));var d=document.createElement("div");d.className="progressName";d.appendChild(document.createTextNode(a.name));var f=document.createElement("div");f.className="progressBarInProgress";var e=document.createElement("div");e.className="progressBarStatus";e.innerHTML="&nbsp;";this.fileProgressElement.appendChild(b);this.fileProgressElement.appendChild(d);this.fileProgressElement.appendChild(e);
this.fileProgressElement.appendChild(f);this.fileProgressWrapper.appendChild(this.fileProgressElement);document.getElementById(c).appendChild(this.fileProgressWrapper)}this.height=this.fileProgressWrapper.offsetHeight;this.setTimer(null)}FileProgress.prototype.setTimer=function(a){this.fileProgressElement.FP_TIMER=a};FileProgress.prototype.getTimer=function(){return this.fileProgressElement.FP_TIMER||null};
FileProgress.prototype.reset=function(){this.fileProgressElement.className="progressContainer";this.fileProgressElement.childNodes[2].innerHTML="&nbsp;";this.fileProgressElement.childNodes[2].className="progressBarStatus";this.fileProgressElement.childNodes[3].className="progressBarInProgress";this.fileProgressElement.childNodes[3].style.width="0%";this.appear()};
FileProgress.prototype.setProgress=function(a){this.fileProgressElement.className="progressContainer ing";this.fileProgressElement.childNodes[3].className="progressBarInProgress";this.fileProgressElement.childNodes[3].style.width=a+"%";this.appear()};
FileProgress.prototype.setComplete=function(){this.fileProgressElement.className="progressContainer blue";this.fileProgressElement.childNodes[3].className="progressBarComplete";this.fileProgressElement.childNodes[3].style.width="";var a=this;this.setTimer(setTimeout(function(){a.disappear()},1E4))};
FileProgress.prototype.setError=function(){this.fileProgressElement.className="progressContainer red";this.fileProgressElement.childNodes[3].className="progressBarError";this.fileProgressElement.childNodes[3].style.width="";var a=this;this.setTimer(setTimeout(function(){a.disappear()},5E3))};
FileProgress.prototype.setCancelled=function(){this.fileProgressElement.className="progressContainer";this.fileProgressElement.childNodes[3].className="progressBarError";this.fileProgressElement.childNodes[3].style.width="";var a=this;this.setTimer(setTimeout(function(){a.disappear()},2E3))};FileProgress.prototype.setStatus=function(a){this.fileProgressElement.childNodes[2].innerHTML=a};
FileProgress.prototype.toggleCancel=function(a,c){this.fileProgressElement.childNodes[0].style.visibility=a?"visible":"hidden";if(c){var b=this.fileProgressID;this.fileProgressElement.childNodes[0].onclick=function(){c.cancelUpload(b);return false}}};
FileProgress.prototype.appear=function(){if(this.getTimer()!==null){clearTimeout(this.getTimer());this.setTimer(null)}if(this.fileProgressWrapper.filters)try{this.fileProgressWrapper.filters.item("DXImageTransform.Microsoft.Alpha").opacity=100}catch(a){this.fileProgressWrapper.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity=100)"}else this.fileProgressWrapper.style.opacity=1;this.fileProgressWrapper.style.height="";this.height=this.fileProgressWrapper.offsetHeight;this.opacity=100;this.fileProgressWrapper.style.display=
""};
FileProgress.prototype.disappear=function(){if(this.opacity>0){this.opacity-=15;if(this.opacity<0)this.opacity=0;if(this.fileProgressWrapper.filters)try{this.fileProgressWrapper.filters.item("DXImageTransform.Microsoft.Alpha").opacity=this.opacity}catch(a){this.fileProgressWrapper.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity="+this.opacity+")"}else this.fileProgressWrapper.style.opacity=this.opacity/100}if(this.height>0){this.height-=4;if(this.height<0)this.height=0;this.fileProgressWrapper.style.height=this.height+
"px"}if(this.height>0||this.opacity>0){var c=this;this.setTimer(setTimeout(function(){c.disappear()},30))}else{this.fileProgressWrapper.style.display="none";this.setTimer(null)}};