function cancelQueue(a){a.stopUpload();var d;do{d=a.getStats();a.cancelUpload()}while(d.files_queued!==0)}function fileDialogStart(){}function fileQueued(a){try{var d=new FileProgress(a,this.customSettings.progressTarget);d.setStatus("\uc5c5\ub85c\ub4dc Ready...");d.toggleCancel(true,this)}catch(b){this.debug(b)}}
function fileQueueError(a,d,b){try{if(d===SWFUpload.QUEUE_ERROR.QUEUE_LIMIT_EXCEEDED)alert("\ub300\uae30\uc5f4\uc5d0 \ud30c\uc77c\uc774 \ub108\ubb34 \ub9ce\uc2b5\ub2c8\ub2e4\n"+(b===0?"\ud5c8\uc6a9\ub41c \uc5c5\ub85c\ub4dc \uc81c\ud55c\uac1c\uc218\ub97c \ucd08\uacfc\ud558\uc600\uc2b5\ub2c8\ub2e4.":b+" \uac1c\uc758 \ud30c\uc77c\uc744 \ub354 \uc5c5\ub85c\ub4dc \ud558\uc2e4 \uc218 \uc788\uc2b5\ub2c8\ub2e4."));else{var c=new FileProgress(a,this.customSettings.progressTarget);c.setError();c.toggleCancel(false);
switch(d){case SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT:c.setStatus("\uc81c\ud55c\uc6a9\ub7c9 \ucd08\uacfc");this.debug("Error : \uc81c\ud55c\uc6a9\ub7c9 \ucd08\uacfc, File name: "+a.name+", File size: "+a.size+", Message: "+b);break;case SWFUpload.QUEUE_ERROR.ZERO_BYTE_FILE:c.setStatus("0byte \ud30c\uc77c");this.debug("Error : \ud30c\uc77c \ud06c\uae30\uac00 0byte\uc785\ub2c8\ub2e4, File name: "+a.name+", File size: "+a.size+", Message: "+b);break;case SWFUpload.QUEUE_ERROR.INVALID_FILETYPE:c.setStatus("\uc9c0\uc6d0\ub418\uc9c0 \uc54a\ub294 \ud30c\uc77c\ud615\uc2dd");
this.debug("Error : \uc9c0\uc6d0\ub418\uc9c0 \uc54a\ub294 \ud30c\uc77c\ud615\uc2dd, File name: "+a.name+", File size: "+a.size+", Message: "+b);break;case SWFUpload.QUEUE_ERROR.QUEUE_LIMIT_EXCEEDED:alert("\ud30c\uc77c \uac1c\uc218\uac00 \ucd08\uacfc\ub418\uc5c8\uc2b5\ub2c8\ub2e4.  "+(b>1?b+" \uac1c\uc758 \ud30c\uc77c\uc744 \ub354 \uc5c5\ub85c\ub4dc\ud558\uc2e4 \uc218 \uc788\uc2b5\ub2c8\ub2e4":"\ub354\uc774\uc0c1 \uc5c5\ub85c\ub4dc \ud558\uc2e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4"));break;default:a!==
null&&c.setStatus("\uc624\ub958 \ubc1c\uc0dd");this.debug("Error Code: "+d+", File name: "+a.name+", File size: "+a.size+", Message: "+b)}}}catch(f){this.debug(f)}}function fileDialogComplete(){try{this.getStats();this.startUpload()}catch(a){this.debug(a)}}function uploadStart(a){try{var d=new FileProgress(a,this.customSettings.progressTarget);d.setStatus("\uc5c5\ub85c\ub4dc \uc911...");d.toggleCancel(true,this)}catch(b){}return true}
function uploadProgress(a,d,b){try{var c=Math.ceil(d/b*100),f=new FileProgress(a,this.customSettings.progressTarget);f.setProgress(c);f.setStatus("\uc5c5\ub85c\ub4dc \uc911...")}catch(g){this.debug(g)}}
function uploadSuccess(a,d){try{var b=new FileProgress(a,this.customSettings.progressTarget);b.setComplete();b.setStatus("\uc5c5\ub85c\ub4dc \uc644\ub8cc");b.toggleCancel(false);var c=this.customSettings.file_type,f=this.customSettings.uploadDir,g=this.customSettings.download_url,h=document.domain;if(c=="image"){var e=d.split("|");_mockdata[_mockdata.length]={imageurl:"http://"+h+e[1],filename:e[0],filesize:a.size,imagealign:"C",originalurl:"http://"+h+e[1],thumburl:"http://"+h+e[1],originalwidth:e[2],
originalheight:e[3],width:e[4],height:e[5]}}else if(c=="attach"){e=d.split("|");_mockdata[_mockdata.length]={attachurl:g+"?filepath="+f+"&filename="+e[1],filemime:e[0],filename:e[1],filesize:a.size}}}catch(i){this.debug(i)}}function uploadComplete(){try{this.getStats().files_queued===0?done():this.startUpload()}catch(a){this.debug(a)}}
function uploadError(a,d,b){try{var c=new FileProgress(a,this.customSettings.progressTarget);c.setError();c.toggleCancel(false);switch(d){case SWFUpload.UPLOAD_ERROR.HTTP_ERROR:c.setStatus("Upload Error: "+b);this.debug("Error Code: HTTP Error, File name: "+a.name+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.MISSING_UPLOAD_URL:c.setStatus("Configuration Error");this.debug("Error Code: No backend file, File name: "+a.name+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.UPLOAD_FAILED:c.setStatus("Upload Failed.");
this.debug("Error Code: Upload Failed, File name: "+a.name+", File size: "+a.size+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.IO_ERROR:c.setStatus("Server (IO) Error");this.debug("Error Code: IO Error, File name: "+a.name+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.SECURITY_ERROR:c.setStatus("Security Error");this.debug("Error Code: Security Error, File name: "+a.name+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.UPLOAD_LIMIT_EXCEEDED:c.setStatus("Upload limit exceeded.");this.debug("Error Code: Upload Limit Exceeded, File name: "+
a.name+", File size: "+a.size+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.SPECIFIED_FILE_ID_NOT_FOUND:c.setStatus("File not found.");this.debug("Error Code: The file was not found, File name: "+a.name+", File size: "+a.size+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.FILE_VALIDATION_FAILED:c.setStatus("Failed Validation.  Upload skipped.");this.debug("Error Code: File Validation Failed, File name: "+a.name+", File size: "+a.size+", Message: "+b);break;case SWFUpload.UPLOAD_ERROR.FILE_CANCELLED:this.getStats();
c.setStatus("Cancelled");c.setCancelled();break;case SWFUpload.UPLOAD_ERROR.UPLOAD_STOPPED:c.setStatus("Stopped");break;default:c.setStatus("Unhandled Error: "+error_code);this.debug("Error Code: "+d+", File name: "+a.name+", File size: "+a.size+", Message: "+b)}}catch(f){this.debug(f)}};