<footer>
	<div class="footer">
		<div class="clear pb30"></div>
		<div class="container">
			<a href="/" title="<%=CB_NAME%>" class="footerLogo hoverBt">
				<img alt="<%=CB_NAME%>" src="/skin/default/img/common/foot_logo.png" class="img-responsive" />
			</a>
			<p class="copyrights1">㈜우리원커머스     서울금천구 가산디지털1로 233 (가산동, 에이스하이엔드타워9차) 10층 1015호 </p>
			<p class="copyrights2">Copyright (c) 2017 oorione. co., Ltd All rights reserved.</p>
		</div>
	</div>
</footer>