<div class="header">
  <div class="main-menu navbar">
    <div class="row no-mar">



      <div class="col-xs-5 col-sm-6 col-md-2 col-lg-3 brand no-pad">
        <h1 class="logo">
          <a href="/" title="<%=CB_NAME%>"><img src="/skin/default/img/common/logo2.png" class="" alt="<%=CB_NAME%>" /></a>
        </h1>
      </div>

      <div class="hidden-xs col-xs-12 hidden-sm col-sm-12 col-md-8 col-lg-6 no-pad">
        <div class="gnb_wrap">
          <ul class="gnb nav navbar-nav nav-scroll">

            <li>
               <a href="#company" class="smooth" title="Company">Company</a>
            </li><li>
               <a href="#about" class="smooth" title="About oorione">About oorione</a>
            </li><li>
               <a href="#careers" class="smooth" title="Careers">Careers</a>
            </li><li>
               <a href="#contact" class="smooth" title="Contact us">Contact us</a>
            </li>

          </ul>
        </div>
      </div>

			<div class="col-xs-7 col-sm-6 col-md-2 col-lg-3 no-pad">
        <div class="top_wrap posi-relative">
				 <!--<a href="http://www.oorionemall.com" title="선물세트전용몰 바로가기" class="shop_link" target="_blank">선물세트전용몰 바로가기</a>-->
         <a class="hamburger hamburger--collapse" id="simple-menu" href="#">
            <div class="hamburger-box">
               <div class="hamburger-inner"></div>
            </div>
         </a>

        </div>
      </div>


    </div>

    <div class="mgnb_wrap">
      <div class="container">
        <ul class="mgnb nav-scroll">
          <li>
            <a href="#company" class="smooth hasChild" title="Company">Company</a>
            <ul class="dropdown-menu">
               <li><a href="#company1" class="smooth_li" title="경영이념">경영이념</a></li>
               <li><a href="#company2" class="smooth_li" title="미션 및 비전">미션 및 비전</a></li>
               <li><a href="#company3" class="smooth_li" title="ceo인사말">ceo인사말</a></li>
               <li><a href="#company4" class="smooth_li" title="연혁">연혁</a></li>
               <li><a href="#company5" class="smooth_li" title="조직 및 업무소개">조직 및 업무소개</a></li>
               <li><a href="#company6" class="smooth_li" title="CI소개">CI소개</a></li>
            </ul>
         </li><li>
            <a href="#about" class="smooth hasChild" title="About oorione">About oorione</a>
            <ul class="dropdown-menu">
               <li><a href="#about1" class="smooth" title="업무개요">업무개요</a></li>
               <li><a href="#about2" class="smooth" title="사업분야">사업분야</a></li>
            </ul>
         </li><li>
            <a href="#careers" class="smooth hasChild" title="Careers">Careers</a>
            <ul class="dropdown-menu">
               <li><a href="#careers1" class="smooth_li" title="인재상">인재상</a></li>
               <li><a href="#careers2" class="smooth_li" title="채용공고">채용공고</a></li>
            </ul>
         </li>
	 <!--
	 <li>
            <a href="#service" class="smooth" title="Service">Service</a>
         </li>
	 -->
	 <li>
            <a href="#contact" class="smooth hasChild " title="Contact us">Contact us</a>
            <ul class="dropdown-menu">
               <li><a href="#contact1" class="smooth_li" title="공지사항">공지사항</a></li>
               <li><a href="#contact2" class="smooth_li" title="오시는 길">오시는 길</a></li>
            </ul>
         </li>
        </ul>
      </div>
    </div>
  </div>
</div>