<footer>
	<div class="footer">
		<div class="clear pb30"></div>
		<div class="container">
			<a href="/" title="<%=CB_NAME%>" class="footerLogo hoverBt">
				<img alt="<%=CB_NAME%>" src="/skin/default/img/common/logo2.png" class="img-responsive" />
			</a>
			<p class="copyrights1">|주|우리원커머스  |주|우리원넷  서울특별시 금천구 가산디지털1로 181 (가산동 371-106) 가산 W CENTER 1709, 1710호 </p>
			<p class="copyrights1">대표이사 : 서연태 / 개인정보관리책임자 : 이정율</p>
			<p class="copyrights1">|주|우리원커머스 사업자등록번호 128-81-68404 / |주|우리원넷 사업자등록번호 653-86-00486</p>
			<p class="copyrights2">Copyright (c) 2019 oorione. co., Ltd All rights reserved.</p>
		</div>
	</div>
</footer>
<div id="notice_view"></div>