<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3 md-margin-bottom-20">
        <div class="headline">
          <h2>Notice</h2>
        </div>
        <div class="row notice" id="notice">        
        </div>
      </div>
      <div class="col-md-3 md-margin-bottom-20">
        <div class="headline">
          <h2>About us</h2>
        </div>
        <ul class="list-unstyled link-list">
          <li><a href="<%=LINK_COMPANY_INTRODUCTION%>">Company</a><i class="fa fa-angle-right"></i></li>
          <li><a href="<%=LINK_COMPANY_CEOMESSAGE%>">Ceo Message</a><i class="fa fa-angle-right"></i></li>
          <li><a href="<%=LINK_COMPANY_HISTORY%>">History</a><i class="fa fa-angle-right"></i></li>
          <li><a href="<%=LINK_COMPANY_MAP%>">Map</a><i class="fa fa-angle-right"></i></li>
        </ul>
      </div>
      <div class="col-md-3 md-margin-bottom-20">
        <div class="headline">
          <h2>Customer</h2>
        </div>
        <ul class="list-unstyled link-list">
          <li><a href="<%=LINK_NOTICE%>">Notice</a><i class="fa fa-angle-right"></i></li>
          <li><a href="<%=LINK_QNA%>">Q&amp;A</a><i class="fa fa-angle-right"></i></li>
          <li><a href="<%=LINK_FAQ%>">FAQ</a><i class="fa fa-angle-right"></i></li>
        </ul>
      </div>
      <div class="col-md-3 map-img md-margin-bottom-20">
        <div class="headline">
          <h2>Contact Us</h2>
        </div>
        <address class="md-margin-bottom-40">
        <a href="tel:<%=CB_TEL%>">
        <h3><i class="fa fa-phone"></i> <%=CB_TEL%></h3>
        </a>
        <a href="mailto:<%=CM_EMAIL%>"><i class="fa fa-envelope-o"></i> <%=CM_EMAIL%></a><br>
         업무시간: 09:00~18:00 </address>
      </div>
    </div>
  </div>
</div>

<div class="copyright">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul>
          <li><a href="<%=LINK_COMPANY_INTRODUCTION%>">회사소개</a></li>
          <li class="devider"></li>
          <li><a href="<%=LINK_MEMBER_PRIVACY%>">개인정보보호정책</a></li>
          <li class="devider"></li>
          <li><a href="<%=LINK_MEMBER_CLAUSE%>">이용약관</a></li>
          <li class="devider"></li>
          <li><a href="<%=LINK_CUSTOMER%>">고객센터</a></li>
          <li class="devider"></li>
          <li><a href="<%=LINK_CONSULT%>">온라인문의</a></li>
          <li class="devider"></li>
          <li><a href="<%=LINK_COMPANY_MAP%>">찾아오시는길</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <p>
          <%=CB_ADDR%>&nbsp;&nbsp;<%=CB_NAME%> &nbsp;<font color="#CCCCCC">l</font>&nbsp; 대표자 : <%=CB_CEO%> &nbsp;<font color="#CCCCCC">l</font>&nbsp; 사업자등록번호 : <%=CB_CORPNUM%><br>
           개인정보책임자 : <%=CM_NAME%> &nbsp;<font color="#CCCCCC">l</font>&nbsp; TEL : <%=CB_TEL%> &nbsp;<font color="#CCCCCC">l</font>&nbsp; FAX : <%=CB_FAX%> &nbsp;<font color="#CCCCCC">l</font>&nbsp; 이메일 : <%=CM_EMAIL%>
          &nbsp;<font color="#CCCCCC">l</font>&nbsp;호스팅 정보 제공자 : (주)헬로웹<br>
           Copyright ⓒ <%=CS_NAME%>. ALL Rights Reserved.
        </p>
      </div>
      <div class="col-md-4">
        <div class="pull-right">
          <%=BOTTOMLOGO%>
        </div>
      </div>
    </div>
  </div>
</div>

